/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: D:\codes\Cyclone_Version_Apps\test_cyclonedds\test_cyclonedds\HelloWorldData.idl
  Source: HelloWorldData.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "HelloWorldData.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace HelloWorldData
{
std::ostream& operator<<(std::ostream& os, Msg const& rhs)
{
  (void) rhs;
  os << "[";
  os << "message: " << rhs.message();
  os << "]";
  return os;
}

} //namespace HelloWorldData

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::HelloWorldData::Msg>() {
  static std::mutex mtx;
  static propvec props;
  static std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed))
    return props;
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed))
    return props;
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::message

  entity_properties_t::finish(props, keylist);
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

