/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: D:\codes\Cyclone_Version_Apps\cyclonev1.2_test\teleop_imu\ControlData.idl
  Source: ControlData.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "ControlData.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace ControlData
{
std::ostream& operator<<(std::ostream& os, imu_data const& rhs)
{
  (void) rhs;
  os << "[";
  os << "acc: " << rhs.acc();
  os << ", gyro: " << rhs.gyro();
  os << ", angle: " << rhs.angle();
  os << ", msg: " << rhs.msg();
  os << "]";
  return os;
}

} //namespace ControlData

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::ControlData::imu_data>() {
  static std::mutex mtx;
  static propvec props;
  static std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed))
    return props;
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed))
    return props;
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::acc
  props.push_back(entity_properties_t(1, 1, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::gyro
  props.push_back(entity_properties_t(1, 2, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::angle
  props.push_back(entity_properties_t(1, 3, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::msg

  entity_properties_t::finish(props, keylist);
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

